### ISSUE TITLE
Tracking bug for migrating to separate build volume

### ISSUE THREAD

**Issue by milkypostman** [melpa/melpa#7840]
On the build server we currently have as single volume to store everything the server does. I am planning on bringing up a new 50GB volume that is just for Nginx logs and MELPA build stuff.

To transition I'll do the following,

1. [x] Bring down the log processor. This will stop stats from updating but is not necessary for basic functionality.
2. [x] Rough sync to get a majority of data.
3. [x] Update the path mounts in the docker config in the repo.
4. [ ] Bring down all the containers
5. [ ] Do a final sync
4. [ ] Start all the containers. This should get the new mount points.

**Comment by milkypostman** [comment]
Whoops, this is done :)
